In [3]:
import numpy as np

# Criando duas matrizes 3x3
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[9, 8, 7], 
              [6, 5, 4], 
              [3, 2, 1]])

In [4]:
print("Matriz A:")
print(A)

Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print("\nMatriz B:")
print(B)


Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [6]:
# Soma das matrizes
soma = A + B
print("\nSoma de A + B:")
print(soma)


Soma de A + B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
# Multiplicação element-wise (cada elemento é multiplicado individualmente)
multiplicacao_elementwise = A * B
print("\nMultiplicação elemento a elemento (A * B):")
print(multiplicacao_elementwise)


Multiplicação elemento a elemento (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
